version: '3'
services:
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
